#ifndef CARTESIANIMPEDANCECONTROLLER_H
#define CARTESIANIMPEDANCECONTROLLER_H

// ==============================================================================
// Include
// ==============================================================================

#include <iostream>
#include <thread>
#include <math.h>
#include <chrono>

#include <cartesian_interface/CartesianInterfaceImpl.h> // For the solver
#include <RobotInterfaceROS/ConfigFromParam.h>  // Model param config
#include <XBotInterface/ModelInterface.h>   // Model generation
#include <XBotInterface/RobotInterface.h>   // Robot generation
#include <xbot2/xbot2.h>
#include <xbot2/hal/dev_ft.h>
#include <Eigen/Core>
#include <Eigen/Geometry>
#include <eigen_conversions/eigen_msg.h>
#include <awesome_utils/awesome_utils/sign_proc_utils.hpp>

// ==============================================================================
// Namespace
// ==============================================================================

using namespace std;
using namespace XBot;

// ==============================================================================
// Class
// ==============================================================================

/**
 * @brief The CartesianImpedanceController class
 */
class CartesianImpedanceController
{

public:

    // ==============================================================================
    // Constructor and Destructor
    // ==============================================================================

    CartesianImpedanceController();

//    CartesianImpedanceController(ModelInterface::Ptr model,
//                                 const string end_effector_link_name,
//                                 const string root_link_name = "base_link");

//    CartesianImpedanceController(ModelInterface::Ptr model,
//                                 const string end_effector_link_name,
//                                 const string root_link_name,
//                                 Eigen::Matrix6d stiffness = Eigen::Matrix6d::Identity());

    CartesianImpedanceController(ModelInterface::Ptr model,
                                 Eigen::Matrix6d stiffness,
                                 const string end_effector);

    //~CartesianImpedanceController();

    // ==============================================================================
    // Additional Functions
    // ==============================================================================

    /**
     * @brief compute_force is the function that given all the error of acc, vel and pos compute the virtual force of
     * the damper and spring system, using the previously updated operational space inertia, stiffness and damping matrix.
     * This function is intended to be called every iteration of a cycle, in order to obtain at each instant of time _dt
     * a new value of the virtal force generated by the displacement from the reference value of the spring/damper system
     * @return return the wrench containig the force and moment
     */
    Eigen::VectorXd compute_torque();

    void update_model(ModelInterface::Ptr);

    // ==============================================================================
    // Setter and Getter
    // ==============================================================================

    /**
     * @brief Set the stiffness matrix to a new value.
     *
     * This function sets the stiffness matrix to the specified Eigen::Matrix6d.
     *
     * @param new_K The new stiffness matrix.
     */
    void set_stiffness(const Eigen::Vector6d &new_K);

    /**
     * @brief Reset the stiffness matrix to a default value.
     *
     * This function resets the stiffness matrix to a default or initial value.
     * Use this when you want to clear or reset the stiffness matrix.
     */
    void set_stiffness();

    /**
     * @brief set_reference_value sets the reference values used to compute the error in the impedance dynamic
     * @param acc_ref is the reference acceleration value of the end effector
     * @param vel_ref is the reference velocity value of the end effector
     * @param pos_ref is the reference position value of the end effector
     */
    void set_reference_value();

    /**
     * @brief setEnd_effector_link set the name of the end effector link, empty string by default.
     * @param newEnd_effector_link the new value.
     */
    void setEnd_effector_link(const string &newEnd_effector_link);


private:

    // ==============================================================================
    // Variables
    // ==============================================================================

    double _dt; // sampling time
    double _n_joints = 6; // number of joints

    string _root_link = "base_link";    // name of the root link, base_link by default
    string _end_effector_link = ""; // name of the end effector link, empty string by default

    XBot::ModelInterface::Ptr _model;

    //RobotChain& _leg;

    JointNameMap _ctrl_joint;

    // Reference acceleration, velocity, position of the end-effector w.r.t. to the base link. By default equal to zero
    Eigen::Vector6d _xddot_ref, _xdot_ref, _x_ref;

    // Actual acceleration, velocity, position of the end-effector w.r.t. to the base link
    Eigen::Vector6d _xddot_real, _xdot_real, _x_real;
    Eigen::Vector6d _xdot_prec; // used for the computation of the acceleration that is done by dv/dt

    // Error between the actual and reference values
    Eigen::Vector6d _eddot, _edot, _e;

    // Cartesian Controller
    Eigen::Matrix6d _K_omega, _D_zeta;   // diagonal matrix that represent the elementary stiffness and damping of the Cartesian axis
    Eigen::Matrix6d _K, _D; // computed stiffness and damping matrix

    // Generic Matrix
    Eigen::Matrix6d _op_sp_inertia; // operational space inertial matrix, usually referred to as Λ
    Eigen::MatrixXd _J; // Jacobian matrix between the root link and the end effector
    Eigen::MatrixXd _B_inv; // inertia matrix in joint space
    Eigen::Matrix6d _Q; // resulting matrix from the Cholesky decomposition of the operational space inertia, used in the computation of the damping matrix

    //SVD decomposition
    Eigen::MatrixXd _U;
    Eigen::MatrixXd _V;
    Eigen::VectorXd _S = Eigen::VectorXd(6);
    Eigen::VectorXd _S_pseudo_inverse = Eigen::VectorXd(6);
    double _rho = 0.001;

    SignProcUtils::MovAvrgFilt _velocity_filter;   // Moving average filter of the velocity, used to compute the acceleration through numerical derivative

    // ==============================================================================
    // Additional Functions
    // ==============================================================================

    /**
     * @brief cholesky_decomp compute the Cholesky decomposition of the operational space inertia
     * in order to obtain the matrix Q used in the computation of stiffness (K) and damping (D)
     */
    Eigen::Matrix6d cholesky_decomp(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B);

    /**
     * @brief matrix_sqrt compute the square root of each elements of the matrix
     * @param matrix
     * @return the square root of the input matrix
     */
    Eigen::Matrix6d matrix_sqrt(Eigen::Matrix6d matrix);

    /**
     * @brief isPositiveDefinite
     * @param matrix
     * @return
     */
    void isPositiveDefinite(const Eigen::MatrixXd& matrix);

    /**
     * @brief Updates the operational space inertia matrix Λ and computes the Cholesky factor Q.
     *
     * This function updates the operational space inertia matrix Λ using the formula Λ = (J * B¯¹ * J)¯¹,
     * where J is the current relative Jacobian and B¯¹ is the current inverse of the joint space inertia matrix B.
     * Its Cholesky decomposition is computed to obtain the lower triangular matrix Q. The updated matrices
     * are stored internally for further use.
     */

    void update_inertia();

    /**
     * @brief update_K_omega is a function that computes the new value of the natural frequency due to the change
     * in the operational space inertia matrix
     */
    void update_K_omega();

    /**
     * @brief update_D compute the new value of the damping matrix after computing Q and the natural frequency matrix _K_omega
     */
    void update_D();

    /**
     * @brief update_real_value will get from the model the updated parameters of the end effector (pos, vel, acc), that are
     * used to compute the error in the impedance controller.
     */
    void update_real_value();

    /**
     * @brief compute_error compute the error between the reference and real values.
     * It must be done after getting the updated values of the acceleration, velocity, position of the
     * end-effector.
     */
    void compute_error();

    /**
     * @brief svd_inverse compute the inverse of a matrix using SVD decomposition
     *
     * In this function the input matrix is singular (so not full rank), so it is not invertible. Therefore is possible
     * to use the dirty & quick method of the inverse using the SVD
     * @param matrix that has to be inverted
     * @return the inverted matrix using the explained method
     */
    Eigen::Matrix6d  svd_inverse(Eigen::Matrix6d matrix);

    double f(double x);

};

#endif // CARTESIANIMPEDANCECONTROLLER_H
